### ISSUE TITLE
Helper app-version config has no effect

### ISSUE THREAD

**Issue by hanssen** [lifeart/ember-ast-hot-load#11]
I use the [ember-cli-app-version](https://github.com/ember-cli/ember-cli-app-version) plugin which resides in "node_modules/ember-cli-app-version/app/helpers/app-version.js".

The console mentions to `add "app-version" into "ember-cli-build.js" in application config section`.

When I copy and paste the config code 
```    
let app = new EmberApp(defaults, {
  'ember-ast-hot-load': {
    helpers: ["app-version"],
    enabled: true
  }
});
```
into my ember-cli-build.js and restart the server, the message still appears and my app is still broken.

I also have problems understanding the first two code examples in the _How to use this addon_ section.

Is there a special issue with helpers provided by foreign plugins?

**Comment by lifeart** [comment]
@hanssen thanks for report! Can you provide `ember-cli`, `ember-source` versions? I think we can fix you issue. (as short-term fix, you can add `app-version` into this array - https://github.com/lifeart/ember-ast-hot-load/blob/master/lib/ast-transform.js#L23)

**Comment by lifeart** [comment]
also, if you have time to create mvp bug  repo, it will be great!

**Comment by hanssen** [comment]
Thank you for the immediate response!

I use `"ember-cli": "~3.3.0"` and `"ember-source": "^3.1.3"`.

Extending the mentioned array did not fix the error. The console message does not appear any more, but my app breaks silently, without any console errors or warnings (as before).

**Comment by lifeart** [comment]
@hanssen can you try `ember-ast-hot-load@0.0.46`?

**Comment by hanssen** [comment]
@lifeart I tried 0.0.46 the info containing the config example code does not appear any more. But some code still breaks silently. I discovered the app-version plugin seems to work in 0.0.44 as well as 0.0.46, the output appears on the page. Another component is breaking, I have broken CSS and a webcam video shoud appear, but does not.

I tried the ember-ast-hot-load plugin in another project. After first start the console mentioned an `this.*` attribute in a computed property component was not defined. I added a handling for that. After that no errors appeared, but the component did not work (menu doesn't open after click). After rolling back, all worked again.

Unfortunately both projects are complex and commercial, so I can't easily provide examples.

I wonder why I get broken behaviour without any console errors? I have no clue where to look into.

Thank you for your effort, I guess I will try it again in a while. If you want me to check further versions, feel free to contact me.

**Comment by lifeart** [comment]
@hanssen thank you for debugging! Can you provide "broken parts" hbs code? (I need to check how AST transform work with it)

**Comment by hanssen** [comment]
@lifeart I created https://github.com/vepro-dev/hot-reload. If you clone it, the "pretty toggle" shows a checkbox. No errors in the console. If you remove the _ember-ast-hot-load_ plugin the "pretty toggle" shows a sliding toggle button. The styling fails with the plugin.

**Comment by lifeart** [comment]
Yeah, I can confirm some stange dom behavour, root cause may be "jquery-dom-manipulations" in semantic-ui, but I'm continue to digging 

![image](https://user-images.githubusercontent.com/1360552/49207611-7b269380-f3c6-11e8-9164-4acaf184312d.png)

**Comment by lifeart** [comment]
@hanssen try `0.0.47` issue fixed

**Comment by hanssen** [comment]
@lifeart version `0.0.47` is not available yet?

**Comment by lifeart** [comment]
@hanssen just published, https://www.npmjs.com/package/ember-ast-hot-load

**Comment by hanssen** [comment]
@lifeart It works now - I tested both big projects I work on. It's really a great benefit to keep the current application state, when working on components! Thank you so much for your support!
