### ISSUE TITLE
Page reload instead of Hot Reload (MU + sparkles)

### ISSUE THREAD

**Issue by gossi** [lifeart/ember-ast-hot-load#16]
Hey,

I gave this addon a try. I've tried it with cutting edge technology, like MU and sparkles, ember-css-modules, decorators (the cool octane stuff!). It may be, because of this but this addon is not hot reloading but the page itself reloads. I can see the console output about the correct resource that should be reloaded though the whole page is refreshed instead.

Here is the repo I'm currently tested it with: https://github.com/gossi/shiny-components

PS. I first thought, that private components (those for each route) aren't hot reloaded because they live in the respective route folder but also the one in `components/` wasn't hot reloading. Let me know if I can assist any further here.

**Comment by lifeart** [comment]
@gossi, thanks for feedback! I'm on it

**Comment by lifeart** [comment]
Can't run example app due to this error:
```
WARNING: @ember-decorators/babel-transforms: You are using an unsupported ember-cli-babel version, decorator/class-property transforms will not be included automatically
WARNING: The 'ember-decorators' addon is using an older version of ember-cli-typescript that uses stage 1 decorators. Please update to ember-cli-typescript@v2 to remove your dependency on legacy decorators.
src/ui/routes/patterns/inheritance/-components/modal/component.ts(7,96): error TS1005: '?' expected.
src/ui/routes/patterns/inheritance/-components/modal/component.ts(7,96): error TS1005: '?' expected.
JSReloader watches js|ts|hbs
broccoli-babel-transpiler is opting out of caching due to a plugin that does not provide a caching strategy: `function resolveRelativeModulePath(name, child) {
  return moduleResolve(name, getRelativeModulePath(child));
}`.
Build Error (Funnel)

ENOENT: no such file or directory, mkdir 'C:\Users\lifeart\AppData\Local\Temp\broccoli-20268CduT2W2KHv7X\out-225-funnel/shiny-components\src/'
```

**Comment by gossi** [comment]
Oupsi, pushing helps. Repo updated ;)

**Comment by lifeart** [comment]
@gossi, can you check againist `ember-ast-hot-load@0.0.52`? 
* looks like route templates now hot-reloaded
* single named 2 levels scoped components support
(foo/bar will work)

https://github.com/lifeart/ember-ast-hot-load/pull/19/files#diff-57d4324420c0fb7b3b5a74262fa07ef6R221

**Comment by lifeart** [comment]
Also, test repo works for me after `ember-css-modules` removal (looks like it has `path` resolution issues on Windows)

**Comment by lifeart** [comment]
Looks like all existing issues fixed in `ember-ast-hot-load@0.0.57`, we definitely should test it and close this ticker if all "ok".

**Comment by lifeart** [comment]
Alot of `MU` related changes in `0.0.64`

**Comment by gossi** [comment]
Just tested, it works amazing. Terrific job here!
