### ISSUE TITLE
Yarn Workspace Support

### ISSUE THREAD

**Issue by donaldwasserman** [lifeart/ember-ast-hot-load#254]
Hi there - 

Encountered this issue attempting to convert my project into a yarn workspace. Wanted to document this here for future reference.

```
UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, lstat '/var/folders/24/5940d3p56rdbyw7yngx2jnp00000gp/T/broccoli-98842Vf8NWDES0BdB/out-784-broccoli_merge_trees_tree_merger_custom_transform_amd/../node_modules/ember-source/dist/ember-template-compiler.js'
```

**Comment by lifeart** [comment]
Hi @donaldwasserman! Thank you for report, could you workaround from readme? https://github.com/lifeart/ember-ast-hot-load#cannot-find-module

**Comment by donaldwasserman** [comment]
@lifeart Thanks for getting back so quickly. Here's the config I'm using for my root package.json

```
  "workspaces": {
    "packages": [
      "A", //ast-hot-load required here
      "B"
    ],
    "nohoist": [
      "**/ember-ast-hot-load"
    ]
  }
```
with `nohoist`, the package gets installed in `A/node_modules` but the error still throws. This is the first time i've ever setup a yarn workspace, so am just randomly changing config.

**Comment by lifeart** [comment]
@donaldwasserman could you try add `**/ember-source` into nohoist?
is it yarn 2.0 ?

**Comment by donaldwasserman** [comment]
So, I am using yarn 1.x, but adding ember source to nohoist worked out great. 

I'd be happy to update the docs to make a little more clear if you want.

**Comment by lifeart** [comment]
@donaldwasserman thank you! PR for docs will be great!
