### ISSUE TITLE
Update addon to work with latest Ember release(s).

### ISSUE THREAD

**Issue by alexabreu** [lifeart/ember-ast-hot-load#358]
It appears the build is breaking for release, beta, and canary channels, but passes for older Ember 2.X versions. Is this expected? What is needed to get this working with recent Ember releases?

**Comment by lifeart** [comment]
@alexabreu it should work with pre-octane. Poking on it to get working with latest ember https://github.com/lifeart/ember-ast-hot-load/pull/328

**Comment by lifeart** [comment]
@alexabreu just checked for 3.20, looks like it's working, issue likely in CI itself
