### ISSUE TITLE
Installing ember-ast-hot-load disables all reload functionality on brand new ember app

### ISSUE THREAD

**Issue by jowi-dev** [lifeart/ember-ast-hot-load#445]
Hey! I really was excited to find this plugin, and I would prefer to use it with usePods:true, here is my issue:

Ember version: 3.21.2
Node Version: 12.14.0
OS: x64 Ubuntu 20.0.4

1) ember new <AppName>
2) ember install ember-ast-hot-load
3) ember s
4) ember g component test-hotload
5) open up localhost:4200, delete the welcome component from application.hbs, add the <TestHotload /> component
6) go to test-hotload.hbs, add "Hello world"

Result: App does not reload as expected, but component does not update content at all without refreshing the page manually.

Is there any setup I'm missing? I've tried this on an existing application as well as a new one. I've added 'ember-ast-hotload' to the ember-cli-build config with enabled:true just to see if that would work and no dice. I would love to see this work as I think it would greatly improve development velocity. Thanks!

**Comment by lifeart** [comment]
Hi, @jowi-dev, could you try same on 1.0.1 version?

**Comment by jowi-dev** [comment]
On the 1.0.1 version now - same result. I see in the terminal via morgan that the update is happening, "Get ...../template.hbs" but the change isn't reflected in the browser until I refresh. Any ideas?

**Comment by jowi-dev** [comment]
@lifeart Yeah Its just fresh start app. I'll push it up to a repo tonight and send you the link here. The component is rendered inside application.hbs

**Comment by jowi-dev** [comment]
@lifeart so its a bit different of a problem than I thought - hot reload works when I'm using VIM in the terminal, but when I use VSCode it doesn't. https://github.com/jowi-dev/ember-ast-sandbox using 'npm run dev'

**Comment by alexabreu** [comment]
I am seeing the same thing when saving via VS Code v. VIM. Interestingly save doesn't trigger a hot reload in the browser when using Text Edit either. Could this be related to how OS X is handling file names? Did something in this repo recently change around how changed files are parsed?

**Comment by alexabreu** [comment]
@jowi-dev can you try out my patch PR to see if it fixes the problems you encountered? ☝️

**Comment by jowi-dev** [comment]
I will! I'll reply here when I've seen it. Thank you!

**Comment by lifeart** [comment]
`1.2.2` released, @jowi-dev let me know if it's not working for you, I will reopen issue
