### ISSUE TITLE
getWithDefault() deprecation

### ISSUE THREAD

**Issue by vlascik** [lifeart/ember-ast-hot-load#448]
`getWithDefault()` was deprecated recently (https://deprecations.emberjs.com/v3.x/#toc_ember-metal-get-with-default).

It's used in hot-loader service here: https://github.com/lifeart/ember-ast-hot-load/blob/c7a0d88d4507117fb6b04e6890b8a31587c59883/addon/services/hot-loader.js#L302

**Comment by lifeart** [comment]
fixed in ember-ast-hot-load@1.1.1
