### ISSUE TITLE
Hot reload not working for new ember project. 

### ISSUE THREAD

**Issue by alexabreu** [lifeart/ember-ast-hot-load#487]
My team had happily been using `ember-ast-hot-load` since version `0.1.4`. However, a change has recently been introduced which seems to break the hot reloading functionality. We assumed this breakage was related to our own project configuration/dependencies, but I was just able to reproduce the same problem by installing `ember-ast-hot-load` on a brand new ember project. Tried these steps with `ember-cli` 3.08, 3.21, and 3.22:

```
ember new test-app
cd test-app
ember install ember-ast-hot-load
npm start
```

Then, made an arbitrary change to application.hbs and saw the following console output:

```
file changed templates/application.hbs

Build successful (324ms) – Serving on http://localhost:4200/

Slowest Nodes (totalTime >= 5%)          | Total (avg)
-----------------------------------------+-----------
BroccoliMergeTrees (17)                  | 74ms (4 ms)
Package /assets/vendor.js (1)            | 32ms
Concat: Vendor Styles/assets/vend... (1) | 29ms
Packaged Application Javascript (1)      | 28ms
Babel: demo (2)                          | 20ms (10 ms)

Skipping livereload for: app/templates/application.hbs
/Users/ale10280/code/demo/app/templates/application.hbs
Reloading /Users/ale10280/code/demo/app/templates/application.hbs only
GET http://localhost:4200/changed?files=/Users/ale10280/code/demo/app/templates/application.hbs
```

Despite the logging about reloading `application.hbs` no template changes are injected and there is no visual change in the rendered output. You have to hard refresh (since live reload is skipped) in order to see the change you make to `application.hbs`.

**Comment by lifeart** [comment]
may be related - https://github.com/lifeart/ember-ast-hot-load/issues/445

**Comment by alexabreu** [comment]
@lifeart yes, that is very much related. Seems like VS Code is the culprit. I'm going to close this issue and poke around to see if I can track down a VS Code setting which might have changed in a recent release. Thanks for pointing me in the right direction!
