### ISSUE TITLE
Cannot read property 'enabled' of undefined

### ISSUE THREAD

**Issue by mfeckie** [lifeart/ember-ast-hot-load#5]
When trying to consume this addon when I boot our app I get

`Cannot read property 'enabled' of undefined`

The only way I can find to solve it is to edit `index.js` of `ember-ast-hot-loader` in `node_modules` and add

```js
_OPTIONS: {}
```

**Comment by lifeart** [comment]
@mfeckie is addon working correctly after this declaration?
(default _OPTIONS delcaration added to 0.0.41)

**Comment by hugoruscitti** [comment]
I had the same issue, after update to 0.0.41 starts to work fine :)
