### ISSUE TITLE
Components with named blocks are empty

### ISSUE THREAD

**Issue by nwhittaker** [lifeart/ember-ast-hot-load#566]
Named blocks are new to 3.25. When `ember-ast-hot-load` is enabled, components with named blocks aren't rendering them.

The below should render "content", but currently does not:
```
// components/named-blocks.hbs
{{yield to="body"}}

// templates/application.hbs
<NamedBlocks>
  <:body>content</:body>
</NamedBlocks>
```

Also added a usage scenario at https://github.com/nwhittaker/ember-ast-hot-load/commit/70c281108aca856302406c28b9967a97f9a1ecb7.

**Comment by lifeart** [comment]
@nwhittaker thank you for report! `ember-ast-hot-load@2.0.3` published

**Comment by nwhittaker** [comment]
I think that's everything! Thanks again, @lifeart.
