### ISSUE TITLE
404 error when run ember s with --proxy

### ISSUE THREAD

**Issue by hugoruscitti** [lifeart/ember-ast-hot-load#6]
Hi, i see this error when i trying update a component in ember running with the --proxy parameter:

![electronica 2018-11-17 15-45-27](https://user-images.githubusercontent.com/99183/48664591-d16b0c80-ea7f-11e8-8a61-62424fb1900c.png)
 
I think it can be related to "rootURL" parameter, if i run the same ember app without the proxy parameter works fine.

To reproduce this error, i think you can run any ember app with something like:

```
ember s --proxy http://www.google.com
```

btw, this addon is awesome, thanks for create it !!!

**Comment by lifeart** [comment]
@hugoruscitti thanks for reporting, yeah, looks like `ember-cli` can't exclude some requests from proxying, only livereload - https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/server/middleware/proxy-server/index.js#L47

**Comment by lifeart** [comment]
@hugoruscitti can you try `0.0.42`? Added fallback behaviour for script errors, if custom `hot-load` middleware unavailable, we use fallback url (little bit more code to evalute & parse for browser, but result of hot-reloading must be same)
