### ISSUE TITLE
Nested Angle Bracked Invocation Syntax Broken in 3.10.0-beta.5

### ISSUE THREAD

**Issue by donaldwasserman** [lifeart/ember-ast-hot-load#89]
Hey All - I can put together a reduced test case if necessary tomorrow (it's too sunny today), but I just upgraded to ember 3.10-beta series (i'm on beta-5, but not sure if it's specific to that version) and it looks like Nested AngleBracket components get rendered as the string version of their name, ie: 

```html
<h1>Posts</h1>
Blog::PostList
```

This is in a full and working app, so i'm not sure there are other addons that could be causing this problem, but I don't think so.

**EDIT**: This is just since moving to 3.10. In 3.9 with the polyfill, everything seemed to work great.

**Comment by lifeart** [comment]
Hi, @donaldwasserman! Thank you for report! I have some updates for `<Nested::Components />`, it's on `master` branch (not yet released), could you please try to reproduse this issue aganist master branch of this repo?

**Comment by donaldwasserman** [comment]
Hey @lifeart, that branch works on my machine.

**Comment by lifeart** [comment]
@donaldwasserman thank you for testing!
`ember-ast-hot-load@0.0.80` with fix released

**Comment by donaldwasserman** [comment]
Hey @lifeart  - Thanks for packing up that fix. 

I was getting ready to close this out, but when installed `0.0.80`, it did fix the nested components, but it looks like it's no longer respecting the `helpers` hash for usages of `my-helper`.

This is really confusing, because I was looking through the diff on that pr and I don't quite see what the issue could be.
